Sys.App.Icon = {
    downloadhelpdoc: 'icon-downloadhelpdoc',
    exitSystem: 'exit-system',
    addrecord: 'icon-addRecord',
    editrecord: 'icon-editRecord',
    deleterecord: 'icon-deleteRecord',
    refreshrecord: 'icon-refreshRecord',
    filterlocalcompany: 'icon-filterlocal',
    saverecord: 'icon-saverecord',
    viewrecord: 'icon-viewRecord',
    queryrecord: 'icon-queryRecord',
    clearquerycondition: 'icon-clearquerycondition',
    configuration: 'icon-config',
    giveoutusbkey: 'icon-giveoutusbkey',
    relevanceRating: 'icon-relevanceRating',
    reviewCompany: 'icon-reviewCompany',
    addkeyforuser: 'icon-addkeyforuser',
    lockedusbkey: 'icon-lockedusbkey',
    adddocument: 'icon-adddocument',
    upload: 'icon-upload',
    uploadnecessarydocument: 'icon-uploadnecessarydocument',
    viewdocumentaudit: 'icon-viewdocumentaudit',
    viewreviewopinion: 'icon-viewreviewopinion',
    reviewagain: 'icon-reviewagain',
    submittorating: 'icon-submittorating',
    stopreview: 'icon-stopreview',
    saveas: 'icon-saveas',
    documents: 'icon-documents',
    uploadfile: 'icon-uploadfile',
    convertpdfRecord: 'icon-convertpdfRecord',
    resetkey: 'icon-resetkey',
    chartline: 'icon-chartline',
    chartpie: 'icon-chartpie',
    excelexport: 'icon-excelexport',
    userregister:'icon-userregister'
};